# Site settings
lang: de_AT
title: Petra Heer
author: Petra Heer
description: <i>Arresto momentum!</i>
url: https://petra.heer.io
logo: /media/petra.png
accent: petra

# Social links
github_username: null
twitter_username: null

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  input: GFM
  smart_quotes: "sbquo,lsquo,bdquo,ldquo"

paginate_path: /page/:num/
paginate: 5

# Collections
collections:
  hashtags:
    output: true
    permalink: /tags/:path/

# Gem modules
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from
